//#include "00_kavala.sqf";
//#include "01_altisair.sqf";
//#include "02_pyrgos.sqf";
//#include "03_selankano.sqf";
//#include "04_kore.sqf";
//#include "05_zaros.sqf";
//#include "06_docks.sqf";
//#include "07_ghost.sqf";
//#include "08_abdera.sqf";
////#include "09_panochori.sqf";
//#include "10_Skopos.sqf";
//#include "11_SelakanoCoast.sqf";
//#include "12_Altiswest.sqf";
//#include "13_Saltflat.sqf";
//#include "14_Altis_Oilrigs.sqf";

#include "00_North.sqf";
#include "01_Southwest.sqf";
#include "02_central.sqf";